os: linux
dist: xenial
language: ruby
cache: bundler
rvm:
  - 2.5
  - 2.6
  - 2.7
bundler_args: --without development
addons:
  code_climate:
    repo_token: e414c2ec611c0f079b1528c526e96035097b2c4fdfdc7cb5f791b93d3f158e6c
after_success:
    - bundle exec codeclimate-test-reporter
